# Generated by Django 3.2.23 on 2024-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240131_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clip_filter',
            field=models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), ('normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='normal', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='clip',
            field=models.ImageField(blank=True, default='../default_post_oroosj', upload_to='images/'),
        ),
    ]
