# Generated by Django 3.2.23 on 2024-02-28 17:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240131_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clip',
            field=cloudinary.models.CloudinaryField(blank=True, default='../default_post_oroosj', max_length=255),
        ),
    ]
