# Generated by Django 3.2.23 on 2024-02-28 18:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clip',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='video'), upload_to='videos/'),
        ),
    ]
