# Generated by Django 3.2.23 on 2024-01-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_image_profile_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='onwer',
        ),
    ]
