# Generated by Django 3.2.23 on 2024-01-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_owner_profile_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='onwer',
            new_name='owner',
        ),
    ]
